# Generated by Django 5.2.1 on 2025-07-02 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_pdfdocument_file_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfdocument',
            name='file_hash',
        ),
    ]
