# Generated by Django 5.2.1 on 2025-07-08 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_length', models.CharField(choices=[('short', 'Short'), ('medium', 'Medium'), ('long', 'Long')], default='medium', max_length=10)),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('context_memory', models.BooleanField(default=True)),
                ('auto_summary', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
