# Generated by Django 5.2.1 on 2025-07-09 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='auto_summary',
        ),
    ]
